namespace BC.PAYMENT.SQL.Queries
{
    public static class ChangeInvoiceQueries
    {
        public static string GetChangeInvoices => $@"SELECT ID InvoiceId,TRANSACTION_REF InvoiceCode,CUS.*,HEADER_TRANSACTION_VALUES InvoiceAmount,
        CASE WHEN N.STATUS = 'C' THEN 'ChangeInvoice'
        WHEN N.STATUS = 'N' THEN 'NewInvoice'
        WHEN N.STATUS = 'O' THEN 'OldInvoice' END [InvoiceType],
        CREATED_DATE CreatedDate,
        CREATED_BY CreatedBy,
        IS_DIVIDED IsDivided,
        ENTRIES_CODE EntriesCode
        FROM NEW_INVOICE N LEFT JOIN GET_CUSTOMERS_BY_DB_CODE() CUS ON CUS.CustomerCode = N.CUSTOMER_CODE
        WHERE N.DB_CODE = @DB_CODE AND STATUS = @STATUS AND N.CREATED_DATE = @CREATED_DATE;";
        public const string GetLocalInvoice =
            @"SELECT S.ADD_CODE CustomerCode,S.ADD_LINE_1KH CustomerName,INVOICE_NUMBER [InvoiceCode],CREATED_DATE CreatedDate,
            TOTAL_AMOUNT InvoiceAmount,M.MARKET_KHMER_NAME [Market],A.AREA_NAME_KHMER [Area],STORE [Store] FROM TB_BC_CHANGEINVOICE_REPAIR_INVOICE R INNER JOIN SIADD S ON S.ADD_CODE = R.CUSTOMER_CODE
            INNER JOIN TB_BCMARKET M ON M.MARKET_ID = S.MARKET_ID INNER JOIN TB_AREAS A ON A.AREA_ID = S.AREA_ID
            WHERE R.DB_CODE_1 = R.DB_CODE AND CONVERT(DATE,R.CREATED_DATE) BETWEEN @FROM_DATE AND @TO_DATE AND R.DB_CODE = @DB_CODE
            UNION 
            SELECT S.ADD_CODE CustomerCode,S.ADD_LINE_1KH CustomerName,TRANSACTION_CODE [InvoiceCode],R.INVOICE_DATE CreatedDate,
            SUB_TOTAL Total,M.MARKET_KHMER_NAME [Market],A.AREA_NAME_KHMER [Area],STORE [Store] FROM TB_BC_CHANGEINVOICE_EXCHANGE_INVOICE R INNER JOIN SIADD S ON S.ADD_CODE = R.CUSTOMER_CODE
            INNER JOIN TB_BCMARKET M ON M.MARKET_ID = S.MARKET_ID INNER JOIN TB_AREAS A ON A.AREA_ID = S.AREA_ID
            WHERE R.DB_CODE = @DB_CODE AND CONVERT(DATE,R.INVOICE_DATE) BETWEEN @FROM_DATE AND @TO_DATE";

        public const string GetOtherBranchInvoice =
            @"SELECT S.ADD_CODE CustomerCode,S.ADD_LINE_1KH CustomerName,INVOICE_NUMBER [InvoiceCode],CREATED_DATE CreatedDate,
            TOTAL_AMOUNT InvoiceAmount,M.MARKET_KHMER_NAME [Market],A.AREA_NAME_KHMER [Area],STORE [Store] FROM TB_BC_CHANGEINVOICE_REPAIR_INVOICE R INNER JOIN SIADD S ON S.ADD_CODE = R.CUSTOMER_CODE
            INNER JOIN TB_BCMARKET M ON M.MARKET_ID = S.MARKET_ID INNER JOIN TB_AREAS A ON A.AREA_ID = S.AREA_ID
			INNER JOIN TB_BC_CHANGEINVOICE_REPAIR_SEND [SEND] ON [SEND].TRANSACTION_REF = R.INVOICE_NUMBER
            WHERE R.STATUS = 2 AND DB_CODE_1 = @DB_CODE AND [SEND].DB_CODE = @DB_CODE AND CONVERT(DATE,[SEND].SEND_DATE) BETWEEN @FROM_DATE  AND @TO_DATE  AND [SEND].STATUS = 'Received'
            UNION 
            SELECT S.ADD_CODE CustomerCode,S.ADD_LINE_1KH CustomerName,TRANSACTION_CODE [InvoiceCode],R.INVOICE_DATE CreatedDate,
            SUB_TOTAL Total,M.MARKET_KHMER_NAME [Market],A.AREA_NAME_KHMER [Area],STORE [Store] FROM TB_BC_CHANGEINVOICE_EXCHANGE_INVOICE R INNER JOIN SIADD S ON S.ADD_CODE = R.CUSTOMER_CODE
            INNER JOIN TB_BCMARKET M ON M.MARKET_ID = S.MARKET_ID INNER JOIN TB_AREAS A ON A.AREA_ID = S.AREA_ID
            WHERE R.DB_CODE = @DB_CODE AND CONVERT(DATE,R.INVOICE_DATE) BETWEEN @FROM_DATE AND @TO_DATE";

        public const string InsertIfNotExistsInvoice =
            @"INSERT INTO NEW_INVOICE(DB_CODE,TRANSACTION_REF,CUSTOMER_CODE,ACC_NAME_KH,HEADER_TRANSACTION_VALUES,STATUS,CREATED_DATE,CREATED_BY,IS_DIVIDED,ENTRIES_CODE)
                VALUES (@DB_CODE,@TRANSACTION,@CUSTOMER_CODE,@CUSTOMER_NAME,@VALUE,@STATUS,GETDATE(),@CREATED_BY,1,@ENTRIES_CODE)";

        public const string CheckExistInvoice = 
            @"SELECT CAST(CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END AS BIT) IsExists FROM NEW_INVOICE WHERE TRANSACTION_REF = @TRANSACTION AND DB_CODE = @DB_CODE AND CREATED_DATE = CONVERT(DATE,GETDATE())";

        public const string UpdateExistInvoice =
            @"UPDATE NEW_INVOICE SET CUSTOMER_CODE = @CUSTOMER_CODE,ACC_NAME_KH = 
                    @CUSTOMER_NAME,HEADER_TRANSACTION_VALUES = @VALUE,STATUS = @STATUS 
                    WHERE TRANSACTION_REF = @TRANSACTION AND DB_CODE = @DB_CODE AND CONVERT(DATE,CREATED_DATE) = CONVERT(DATE,GETDATE())";
    }
}
