namespace BC.PAYMENT.SQL.Queries;

public static class CustomerQueries
{
    public static string GetCustomerInfoByMarketIdAsync => $@"
        SELECT ANAL.ADD_CODE CustomerCode,ANAL.ACC_CODE CustomerName,SIDADD.DEL_ADD_1KH CustomerNameKhmer
     FROM SIADDANAL ANAL INNER JOIN SIDADD ON SIDADD.ADD_CODE = ANAL.ADD_CODE INNER JOIN BCMC ON BCMC.ADD_CODE = ANAL.ADD_CODE
     WHERE BCMC.MARKET_ID = @MARKET_ID
     GROUP BY ANAL.ADD_CODE, ANAL.ACC_CODE, SIDADD.DEL_ADD_1KH
     ORDER BY ANAL.ADD_CODE ASC";

    public static string GetAllCustomerInfoAsync => $@"
     SELECT SIADD.ADD_CODE CustomerCode,SIADD.ADD_LINE_1 CustomerName,ADD_TEL Tel,STORE Store,TA.ANAL_M0 Area,TA.AREA_NAME AreaDesc,
TA.AREA_NAME_KHMER AreaDescKh,M.ANAD_CODE Market,M.MARKET_NAME MarketDesc,M.MARKET_KHMER_NAME MarketDescKh
,S.ANAL_C6 AreaOS,S1AREA.ANAD_DESC AreaDescOS,S1AREA.ANAD_COM AreaDescKhOS,S.ANAL_C9 MarketOS
,S1AMARKET.ANAD_DESC MarketDescOS,S1AMARKET.ANAD_COM MarketDescKhOS
 FROM SIADD 
FULL OUTER JOIN TB_BCMARKET M ON M.MARKET_ID = SIADD.MARKET_ID
INNER JOIN TB_AREAS TA ON TA.AREA_ID = SIADD.AREA_ID AND TA.DB_CODE = @DB_CODE
LEFT JOIN SIADDANAL S ON SIADD.ADD_CODE = S.ACC_CODE AND S.DB_CODE = @DB_CODE 
LEFT JOIN SIANALD S1AREA ON S.ANAL_C6 = S1AREA.ANAD_CODE AND S1AREA.ANAM_CODE = 'C6' AND S1AREA.DB_CODE =@DB_CODE
LEFT JOIN SIANALD S1AMARKET ON S.ANAL_C9 = S1AMARKET.ANAD_CODE AND S1AMARKET.ANAM_CODE = 'C9' AND S1AMARKET.DB_CODE =@DB_CODE
WHERE SIADD.MARKET_ID IS NOT NULL AND M.DB_CODE = @DB_CODE AND SIADD.DB_CODE = @DB_CODE
AND SIADD.ADD_TYPE = '0' AND ADD_STAT = 'A'
ORDER BY SIADD.ADD_CODE ASC
OFFSET @OFFSET ROWS FETCH NEXT @PAGESIZE ROWS ONLY;";

    public static string GetAllCustomerInfoCountAsync => $@"
     SELECT COUNT(SIADD.ADD_CODE)
 FROM SIADD 
FULL OUTER JOIN TB_BCMARKET M ON M.MARKET_ID = SIADD.MARKET_ID
INNER JOIN TB_AREAS TA ON TA.AREA_ID = SIADD.AREA_ID AND TA.DB_CODE = @DB_CODE
LEFT JOIN SIADDANAL S ON SIADD.ADD_CODE = S.ACC_CODE AND S.DB_CODE = @DB_CODE 
LEFT JOIN SIANALD S1AREA ON S.ANAL_C6 = S1AREA.ANAD_CODE AND S1AREA.ANAM_CODE = 'C6' AND S1AREA.DB_CODE =@DB_CODE
LEFT JOIN SIANALD S1AMARKET ON S.ANAL_C9 = S1AMARKET.ANAD_CODE AND S1AMARKET.ANAM_CODE = 'C9' AND S1AMARKET.DB_CODE =@DB_CODE
WHERE SIADD.MARKET_ID IS NOT NULL AND M.DB_CODE = @DB_CODE AND SIADD.DB_CODE = @DB_CODE
AND SIADD.ADD_TYPE = '0' AND ADD_STAT = 'A';";

    public static string GetCustomerWhoWrongAreaAndMarket => $@"
SELECT FG.CustomerCode,FG.CustomerName,FG.ANAL_M0 AS Area,TB.MARKET_NAME AS MarketDesc,TB.MARKET_KHMER_NAME AS MarketDescKh,
            S.ANAL_C6 AS AreaOS,S1.ANAD_DESC AS MarketDescOS,S1.ANAD_COM AS MarketDescKhOS FROM dbo.FN_GETCUSTOMERS(@DB_CODE) FG
            INNER JOIN TB_BCMARKET TB ON TB.MARKET_ID = FG.MarketId
            INNER JOIN SIADDANAL S ON FG.CustomerCode = S.ACC_CODE AND S.DB_CODE = @DB_CODE
            INNER JOIN SIANALD S1 ON S.ANAL_C9 = S1.ANAD_CODE AND S1.ANAM_CODE = 'C9' AND S1.DB_CODE = @DB_CODE
            WHERE  EXISTS (SELECT 1 FROM SIADDANAL S INNER JOIN SIANALD S1
            ON S.ANAL_C9 = S1.ANAD_CODE AND S1.ANAM_CODE = 'C9'
             WHERE S.ACC_CODE = FG.CustomerCode AND S.DB_CODE = @DB_CODE AND (FG.ANAL_M0 != S.ANAL_C6 
             OR UPPER(TB.MARKET_NAME) <> UPPER(S1.ANAD_DESC)))
";

    public static string GetCustomerImage =>
        @"SELECT PICTURE FROM SIADD WHERE ADD_CODE = @CUSTOMER_ID AND DB_CODE = @DB_CODE";
}