namespace BC.PAYMENT.SQL.Queries;

public static class PaymentInvoiceQueries
{
    public const string SavePaymentInvoice = $@"SAVE_PAYMENT_INVOICE";
    public static string IsExistsHeaderId => $@"SELECT CAST(COUNT(*) AS BIT) IsExists FROM PAYMENT_INVOICE_HEADER WHERE INVOICE_DIVIDEND_DATE = @INVOICE_DIVIDEND_DATE AND DELIVERY_ID = @DELIVERY_ID
            AND DB_CODE = @DB_CODE;";

    public const string CreatePaymentHeader = @"INSERT INTO PAYMENT_INVOICE_HEADER(DB_CODE,DELIVERY_ID,P_PERIOD,ENTRIES_CODE,CREATED_DATE,CREATED_BY,P_STATE,INVOICE_DIVIDEND_DATE)
            OUTPUT INSERTED.ID
            VALUES(@DB_CODE,@DELIVERY_ID,@PERIOD,@ENTRIES_CODE,@CREATED_DATE,@CREATED_BY,@STATUS,@INVOICE_DIVIDEND_DATE)";

    public const string GetPaymentHeaderId = @"SELECT ID FROM PAYMENT_INVOICE_HEADER WHERE DB_CODE = @DB_CODE AND DELIVERY_ID = @DELIVERY_ID AND INVOICE_DIVIDEND_DATE = @INVOICE_DIVIDEND_DATE";
    public static string CreateBcPaymentDetail => @$"BEGIN TRANSACTION;
                IF EXISTS
                (
                    SELECT 1 FROM dbo.BCPAYMENTDETAILA WITH (UPDLOCK, HOLDLOCK) WHERE DELIVERYID = @DID AND CREATED_DATE = @CD
                )
                BEGIN
                    UPDATE dbo.BCPAYMENTDETAILA SET DB_CODE=@DB, TOTAL=@TT, DOLLAR=@D, RIEL=@R, EXCHANGE=@E, DESC_EXP_1=@D1, EXP_AMOUNT_1=@EA1, DESC_EXP_2=@D2, EXP_AMOUNT_2=@EA2, DESC_EXP_3=@D3, EXP_AMOUNT_3=@EA3, MONEY_BIAS=@MB, CREATED_BY=@CB, ENTRIES_CODE=@EC WHERE DELIVERYID=@DID AND CREATED_DATE>=@CD AND CREATED_DATE<DATEADD(DAY,1,@CD);
                END
                ELSE
                BEGIN
                    INSERT INTO dbo.BCPAYMENTDETAILA (DB_CODE, DELIVERYID, TOTAL, DOLLAR, RIEL, EXCHANGE, DESC_EXP_1, EXP_AMOUNT_1, DESC_EXP_2, EXP_AMOUNT_2, DESC_EXP_3, EXP_AMOUNT_3, MONEY_BIAS, CREATED_DATE, CREATED_BY, ENTRIES_CODE) VALUES (@DB, @DID, @TT, @D, @R, @E, @D1, @EA1, @D2, @EA2, @D3, @EA3, @MB, @CD, @CB, @EC);
                END
                COMMIT TRANSACTION;";

    public const string CreatePaymentInvoice = @"IF NOT EXISTS (SELECT 1 FROM PC_PAYMENT_INVOICE WHERE DB_CODE = @DB_CODE AND DIVDIE_INVOICE_ID = @DIVIDED_ID)
            BEGIN
                INSERT INTO PC_PAYMENT_INVOICE(DB_CODE, DIVDIE_INVOICE_ID, PAYMENT_HEADER_ID, AMOUNT, CREATE_BY, CREATED_DATE, STATUS)
                VALUES(@DB_CODE, @DIVIDED_ID, @PAYMENT_HEADER_ID, @AMOUNT, @CREATED_BY, @CREATED_DATE, '1');
            END
            UPDATE PC_DIVIDED_INVOICE SET STATUS = '0' WHERE DIVIDED_INVOICE_ID = @DIVIDED_ID AND DB_CODE = @DB_CODE;";

    public static string GetPaymentInvoiceDetail(string criteria,string addOnFields = "",string addOnGroupBy="",string addReference="",string sortBy = "ORDER BY N.CUSTOMER_CODE") => @$"
        SELECT P.DB_CODE DbCode, P.INVOICE_ID InvoiceId, D.DELIVERIES_KHMER DeliveryName, PAID.PAYMENT_ID PaymentId,
        P.DIVIDED_INVOICE_ID DividedId, N.CUSTOMER_CODE CustomerCode, N.ACC_NAME_KH CustomerName,
        N.TRANSACTION_REF InvoiceCode, 1.00 AS Amount,N.HEADER_TRANSACTION_VALUES InvoiceValue,
        ISNULL(CASE WHEN PAID.AMOUNT < N.HEADER_TRANSACTION_VALUES THEN PAID.AMOUNT END,0) HalfPaid,
        ISNULL(CASE WHEN PAID.AMOUNT >= N.HEADER_TRANSACTION_VALUES THEN PAID.AMOUNT END,0) FullPaid,
        N.HEADER_TRANSACTION_VALUES - PAID.AMOUNT Total,PAID.AMOUNT Paid
        {addOnFields} FROM PC_DIVIDED_INVOICE P
        INNER JOIN NEW_INVOICE N ON N.ID = P.INVOICE_ID INNER JOIN PC_PAYMENT_INVOICE PAID 
        ON PAID.DIVDIE_INVOICE_ID = P.DIVIDED_INVOICE_ID INNER JOIN TB_BCDELIVERIES D 
        ON D.DELIVERIES_ID = P.DELIVERY_ID 
        {addReference}
        {criteria} GROUP BY P.DB_CODE, D.DELIVERIES_KHMER,P.INVOICE_ID,N.CUSTOMER_CODE,
        N.ACC_NAME_KH,N.TRANSACTION_REF,N.HEADER_TRANSACTION_VALUES,
        P.DIVIDED_INVOICE_ID, PAID.PAYMENT_ID, PAID.AMOUNT,
        PAID.PAYMENT_ID, P.DIVIDED_INVOICE_ID {addOnGroupBy} {sortBy};";

    public const string DeletePaymentInvoice = @"
        DELETE FROM PC_PAYMENT_INVOICE WHERE PAYMENT_ID = @PAYMENT_ID;
        IF @@ROWCOUNT > 0
        BEGIN
            IF NOT EXISTS(SELECT 1 FROM PC_RETURN_INVOICE WHERE DIVIDED_INIOVICE_ID = @DII)
                UPDATE PC_DIVIDED_INVOICE SET STATUS = 1 WHERE DIVIDED_INVOICE_ID = @DII;
        END;";

    public static string GetBcPaymentDetail(string condition) => @$"
        SELECT ID Id,
            DB_CODE AS DbCode,
            DELIVERYID AS DeliveryId,
            ISNULL(TOTAL, 0) AS Total,
            ISNULL(DOLLAR, 0) AS Dollar,
            ISNULL(RIEL, 0) AS Riel,
            ISNULL(EXCHANGE, 0) AS Exchange,
            ISNULL(DESC_EXP_1, '') AS DescExp1,
            ISNULL(EXP_AMOUNT_1, 0) AS ExpAmount1,
            ISNULL(DESC_EXP_2, '') AS DescExp2,
            ISNULL(EXP_AMOUNT_2, 0) AS ExpAmount2,
            ISNULL(DESC_EXP_3, '') AS DescExp3,
            ISNULL(EXP_AMOUNT_3, 0) AS ExpAmount3,
            ISNULL(MONEY_BIAS, 0) AS MoneyBias,
            CREATED_DATE AS CreatedDate,
            ISNULL(CREATED_BY, '') AS CreatedBy,
            ISNULL(ENTRIES_CODE, '') AS EntriesCode
        FROM dbo.BCPAYMENTDETAILA
        WHERE DB_CODE = @DB_CODE
          {condition}
        ORDER BY CREATED_DATE DESC;";
}