<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Contracts\Preset\ItemTransaction\"/>
        <Folder Include="Contracts\Transaction\Audit\VerifyInvoice\"/>
        <Folder Include="Contracts\Transaction\DailyPayment\DividingInvoices\Invoice\"/>
        <Folder Include="Contracts\Transaction\Inventory\VerificationRFID\"/>
        <Folder Include="Contracts\Transaction\ProvincialPayment\CheckingStockCarPayment\"/>
        <Folder Include="Entities\CommondityExchange\ExchangeItem\"/>
        <Folder Include="Entities\CommondityExchange\Invoices\"/>
        <Folder Include="Entities\CommondityExchange\Repairer\"/>
        <Folder Include="Entities\Inventory\StockCounting\"/>
        <Folder Include="Entities\Transaction\Inventory\VerificationRFID\"/>
        <Folder Include="Entities\Transaction\ProvincialPayment\ReviewReport\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0"/>
        <PackageReference Include="System.Drawing.Common" Version="8.0.15"/>
    </ItemGroup>

</Project>
